# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: nairaland
    build: .
    command: gunicorn -b 0.0.0.0:5000 nairaland.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/nairaland.db
    volumes:
      - ./nairaland:/code/nairaland
      - ./db/:/db/
    ports:
      - "5000:5000"
